### ISSUE TITLE
Overall a little cumbersome and unclear what the goal really is

### ISSUE THREAD

**Issue by bhabig** [learn-co-curriculum/react-props-and-state-lab#16]
I think a lot of us felt that if more description, maybe even a little video like in jquery ttt was put into the Readme, and LESS starter code in the lab (maybe none at all) it would be more helpful and probably easier to grasp the goal of the lab.

Mainly the order of the Readme and tests could be improved, as @itzsaga says in the other issue. It feels like this is a good opportunity to do some ground-up work, so I also feel less starter code combined with more Readme descriptiveness and direction could make this lab go from confusing to a great mid-term review type of thing.

**Comment by jcpny1** [comment]
ditto. start by providing the final look and functionality. Also, encourage top-down incremental development. For example, the readme seems to encourage creating quite a bit code in pet that can't be tested until higher-level coding is done later on.

**Comment by realAndrewCohn** [comment]
addressed by #19
