### ISSUE TITLE
Test wording unclear

### ISSUE THREAD

**Issue by ValerieHMoore** [learn-co-curriculum/react-props-and-state-lab#26]
The ReadMe says: 
"Once a pet is adopted, they cannot un-adopt it."

The test description says "should toggle a pet's adopted status," which implies changing isAdopted to false if true, and to true if false.

Suggest rewriting line 78 in the test verbiage to reflect "should change isAdopted to true"

Thank you.

**Comment by maxwellbenton** [comment]
Fixed! Thank you @ValerieHMoore!
