### ISSUE TITLE
BDD recommendation

### ISSUE THREAD

**Issue by MoreSaltMoreLemon** [learn-co-curriculum/react-props-and-state-lab#27]
Recommending that we build out the project using BDD, and not worry about passing the tests *then* actually worry about passing the tests when your deliverables weren't precise enough for our code to match the tests is resulting in a working website failing all but 2 of the tests. This is transforming this lab from something focused on learning to focused on debugging why the specific hooks that you have defined into our code are not working. While that is beneficial to an extent, it is beyond frustrating to be told not to worry about the tests, develop our code out and then fail almost all of the tests right out of the box.

Either give better deliverables that point out the properties and method names that we need to define or loosen up on the tests so that we can focus on learning instead.

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
