### ISSUE TITLE
Readme is misleading for how to render button

### ISSUE THREAD

**Issue by racheladaw** [learn-co-curriculum/react-props-and-state-lab#36]
The readme states to pass an **isAdopted prop** to the Pet component and, "Using this prop, render the correct button in the pet's card; if the pet is adopted, show the disabled button. Otherwise, show the primary button to adopt the pet."

However, the test for this passes the prop like so: <Pet **pet={{ ...FEMALE_CAT, isAdopted: true }**} />

If you render the button based on the isAdopted prop, the test will not work, since it expects you to use the pet prop.

**Comment by maxwellbenton** [comment]
Hi @racheladaw,

Thank you for pointing this out! We've updated this lesson's readme to more accurately align with what is expected. `isAdopted` is a property of the `pet` prop, which should resolve this issue for future students. We've also added an additional step for `onAdopt` to help clarify that `isAdopted` is set when the method is called.

Thank you for contributing!
