### ISSUE TITLE
difficult to debug/develop without being able to run dev server

### ISSUE THREAD

**Issue by SophieDeBenedetto** [learn-co-curriculum/react-props-and-state-lab#4]
This lab can only be completed by running `npm test` and trying to decipher error messages that don't always give a lot of info. 

Would be very helpful to provide a dev server students can run in order to debug as they build out the application. 

@AnnJohn

**Comment by AnnJohn** [comment]
@thomastuts would you be able to take a look at this and let us know your thoughts?

**Comment by thomastuts** [comment]
Hi @SophieDeBenedetto, this lab was specifically set up to be able to work anywhere, including in offline mode. Even though we're using `fetch`, the responses are actually [mocked](https://github.com/learn-co-curriculum/react-props-and-state-lab/blob/master/fetch-setup.js).

What error are you getting when opening `index.html`? Did you make sure to run `npm run bundle` before starting the lab? This compiles the source code to a bundle that is loaded in the browser.

**Comment by Lukeghenco** [comment]
This should be resolved now
